### ISSUE TITLE
Atom support

### ISSUE THREAD

**Issue by Kikobeats** [zeke/ghwd#16]
any plan to convert this into a atom plugin? could be AWESOME 😄

**Comment by zeke** [comment]
I made this, which is pretty similar: https://github.com/zeke/atom-npm

Open to ideas on how to improve that package. Feel free to open issues there!

**Comment by Kikobeats** [comment]
Normally my workflow is reviewing in Atom that I want to share, then I copy the path and I paste it at terminal prefixing with ghwd command.

Could be desable simply execute a atom command and open the file in the browser. Very similar to atom-npm, yea!

**Comment by zeke** [comment]
Oh I see.. so you end up running something like `ghwd path/to/file` in your terminal?

**Comment by Kikobeats** [comment]
yep

**Comment by zeke** [comment]
I think Atom comes with that feature by default:

<img width="797" alt="screen shot 2016-07-18 at 7 47 56 am" src="https://cloud.githubusercontent.com/assets/2289/16916777/fe343de0-4cbb-11e6-9e0d-955b8ee6de2f.png">

**Comment by Kikobeats** [comment]
It is, but the name of the menu for do that is:

<img width="497" alt="screen shot 2016-07-28 at 18 17 34" src="https://cloud.githubusercontent.com/assets/2096101/17220448/88c1a9bc-54ef-11e6-8806-ef4df33c7101.png">

Thanks!
